global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@yourdomain.com'
  smtp_auth_username: 'alerts@yourdomain.com'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@yourdomain.com'
    subject: '🚨 PDF Editor - Alerte Critique'
    body: |
      Alerte critique détectée:
      
      {{ range .Alerts }}
      - {{ .Annotations.summary }}
      - Description: {{ .Annotations.description }}
      - Sévérité: {{ .Labels.severity }}
      - Instance: {{ .Labels.instance }}
      {{ end }}
      
      Veuillez intervenir immédiatement.
  
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#alerts'
    color: 'danger'
    title: '🚨 PDF Editor - Alerte Critique'
    text: |
      {{ range .Alerts }}
      *{{ .Annotations.summary }}*
      {{ .Annotations.description }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'admin@yourdomain.com'
    subject: '⚠️ PDF Editor - Avertissement'
    body: |
      Avertissement détecté:
      
      {{ range .Alerts }}
      - {{ .Annotations.summary }}
      - Description: {{ .Annotations.description }}
      - Instance: {{ .Labels.instance }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']