groups:
- name: pdf-editor.rules
  rules:
  
  # Alerte si l'application est down
  - alert: PDFEditorDown
    expr: up{job="pdf-editor"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PDF Editor application is down"
      description: "PDF Editor has been down for more than 1 minute."

  # Alerte sur le taux d'erreur élevé
  - alert: HighErrorRate
    expr: |
      (
        rate(http_requests_total{status_code=~"5.."}[5m]) /
        rate(http_requests_total[5m])
      ) * 100 > 5
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "Error rate is {{ $value }}% for the last 5 minutes."

  # Alerte sur le temps de réponse élevé
  - alert: HighResponseTime
    expr: |
      histogram_quantile(0.95, 
        rate(http_request_duration_seconds_bucket[5m])
      ) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response time detected"
      description: "95th percentile response time is {{ $value }}s."

  # Alerte sur l'utilisation mémoire élevée
  - alert: HighMemoryUsage
    expr: |
      (memory_usage_bytes{type="heapUsed"} / 
       memory_usage_bytes{type="heapTotal"}) * 100 > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is {{ $value }}%."

  # Alerte sur l'utilisation CPU élevée
  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "CPU usage is {{ $value }}%."

  # Alerte sur l'espace disque faible
  - alert: LowDiskSpace
    expr: |
      (
        node_filesystem_avail_bytes{mountpoint="/"} /
        node_filesystem_size_bytes{mountpoint="/"}
      ) * 100 < 20
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low disk space"
      description: "Disk space is {{ $value }}% available."

  # Alerte critique sur l'espace disque très faible
  - alert: CriticalDiskSpace
    expr: |
      (
        node_filesystem_avail_bytes{mountpoint="/"} /
        node_filesystem_size_bytes{mountpoint="/"}
      ) * 100 < 10
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Critical disk space"
      description: "Disk space is critically low: {{ $value }}% available."

  # Alerte sur les opérations PDF échouées
  - alert: HighPDFOperationFailureRate
    expr: |
      (
        rate(pdf_operations_total{status="error"}[5m]) /
        rate(pdf_operations_total[5m])
      ) * 100 > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High PDF operation failure rate"
      description: "PDF operation failure rate is {{ $value }}%."

  # Alerte sur Redis down
  - alert: RedisDown
    expr: up{job="redis"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Redis is down"
      description: "Redis has been down for more than 1 minute."

  # Alerte sur Nginx down
  - alert: NginxDown
    expr: up{job="nginx"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Nginx is down"
      description: "Nginx has been down for more than 1 minute."

  # Alerte sur le nombre de connexions actives élevé
  - alert: HighActiveConnections
    expr: active_connections > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High number of active connections"
      description: "Number of active connections is {{ $value }}."

  # Alerte sur les certificats SSL qui expirent bientôt
  - alert: SSLCertificateExpiringSoon
    expr: |
      (ssl_certificate_expiry_seconds - time()) / 86400 < 30
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: "SSL certificate expiring soon"
      description: "SSL certificate will expire in {{ $value }} days."